---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://authelia.anytypecompute.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: public.anytypecompute.com
      policy: bypass
    - domain: vpnflower.anytypecompute.com
      policy: one_factor
    # - domain: secure.anytypecompute.com
    #   policy: two_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  domain: anytypecompute.com  # Should match whatever your root protected domain is
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: a+kfnBzXgXv1F7EXmcUuDw== #prince
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
...