global:
  scrape_interval: 10s

scrape_configs:
  - job_name: nomad-server
    metrics_path: "/v1/metrics?format=prometheus"
    consul_sd_configs:
      - server: "172.17.0.1:8500"
        services: ["nomad"]
        tags: ["http"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.+"
        target_label: "hostname"
        replacement: "nomad-server-$1"
  - job_name: nomad-client
    metrics_path: "/v1/metrics?format=prometheus"
    consul_sd_configs:
      - server: "172.17.0.1:8500"
        services: ["nomad-client"]
        tags: ["http"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.+"
        target_label: "hostname"
        replacement: "nomad-client-$1"
  - job_name: rabbit-client
    metrics_path: "/metrics?format=prometheus"
    consul_sd_configs:
      - server: "172.17.0.1:8500"
        services: ["prometheus"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.+"
        target_label: "hostname"
        replacement: "rabbit-client-$1"